name: ReaPack

on:
  push:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  reapack:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"
          bundler-cache: false

      - name: Install reapack-index
        run: gem install reapack-index

      - name: Configura il nome del Robottino
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Validate ReaPack packages
        run: reapack-index --check

      - name: Genera e chiudi l'index.xml nel pacco
        run: reapack-index --commit

      - name: Spedisci il pacco al tuo GitHub!
        run: git push
